services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK-ENV=development
    depends_on:
      - redis
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 30s 
      timeout: 10s
      retries: 3 
      start_period: 30s 


  redis:
   image: "redis:alpine"
   ports:  
   - "6379:6379"
   volumes:
     - redis_data:/data

volumes:
      redis_data: